# Generated by Django 5.1.6 on 2025-02-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ticket_prioridad_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('director', 'Director'), ('subdirector', 'Subdirector'), ('jefe_departamento', 'Jefe de Departamento'), ('coordinador', 'Coordinador'), ('usuario', 'Usuario'), ('administrador', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
