# Generated by Django 5.1.6 on 2025-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0004_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(choices=[('coordinacion_general', 'Coordinación General'), ('secretaria_tecnica', 'Secretaria Técnica y Seguimiento Institucional'), ('admin_finanzas', 'Unidad de Administración y Finanzas'), ('juridico', 'Unidad de Apoyo Jurídico'), ('control_interno', 'Órgano Interno de Control'), ('transparencia', 'Unidad de Transparencia'), ('informatica', 'Unidad de Apoyo Técnico e Informático'), ('voluntariado', 'Dirección de Voluntariado y Vinculación Institucional con Sociedad Civil'), ('alimentarios', 'Dirección de Servicios Alimentarios y Desarrollo Comunitario'), ('orientacion_familiar', 'Dirección de Orientación Familiar y Asistencia Social'), ('rehabilitacion', 'Dirección de Rehabilitación e Inclusión'), ('centros_asistenciales', 'Dirección de Centros Asistenciales'), ('proteccion_nna', 'Secretaria Ejecutiva del Sistema Estatal de Protección de los Derechos de Niñas, Niños y Adolescentes'), ('procuraduria_familia', 'Procuraduría Estatal de Protección de la Familia y de los Derechos de las Niñas, Niños y Adolescentes')], default='coordinacion_general', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('director', 'Director'), ('subdirector', 'Subdirector'), ('jefe_departamento', 'Jefe de Departamento'), ('coordinador', 'Coordinador'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
