# Generated by Django 5.1.6 on 2025-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_usuario_direccion_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_archivos/'),
        ),
    ]
