# Generated by Django 5.1.6 on 2025-03-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_ticket_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('director', 'Director'), ('subdirector', 'Subdirector'), ('jefe_departamento', 'Jefe de Departamento'), ('coordinador', 'Coordinador'), ('usuario', 'Usuario'), ('secretaria', 'Secretaria')], default='usuario', max_length=20),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('direccion', 'Dirección'), ('subdireccion', 'Subdirección'), ('departamento', 'Departamento')], max_length=20)),
                ('institucion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subinstituciones', to='gestion.institucion')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='gestion.institucion'),
        ),
    ]
