# Generated by Django 5.1.6 on 2025-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_usuario_institucion_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='direccion',
            field=models.CharField(choices=[('coordinacion_general', 'Coordinación General'), ('secretaria_tecnica', 'Secretaria Técnica y Seguimiento Institucional'), ('admin_finanzas', 'Unidad de Administración y Finanzas'), ('juridico', 'Unidad de Apoyo Jurídico'), ('control_interno', 'Órgano Interno de Control'), ('transparencia', 'Unidad de Transparencia'), ('informatica', 'Unidad de Apoyo Técnico e Informático'), ('voluntariado', 'Dirección de Voluntariado y Vinculación Institucional con Sociedad Civil'), ('alimentarios', 'Dirección de Servicios Alimentarios y Desarrollo Comunitario'), ('orientacion_familiar', 'Dirección de Orientación Familiar y Asistencia Social'), ('rehabilitacion', 'Dirección de Rehabilitación e Inclusión'), ('centros_asistenciales', 'Dirección de Centros Asistenciales'), ('proteccion_nna', 'Secretaria Ejecutiva del Sistema Estatal de Protección de los Derechos de Niñas, Niños y Adolescentes'), ('procuraduria_familia', 'Procuraduría Estatal de Protección de la Familia y de los Derechos de las Niñas, Niños y Adolescentes')], default='coordinacion_general', max_length=50),
        ),
    ]
