# Generated by Django 5.1.6 on 2025-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_ticket_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='subdireccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, choices=[('coordinacion_general', 'Coordinación General'), ('secretaria_tecnica', 'Secretaria Técnica y Seguimiento Institucional'), ('admin_finanzas', 'Unidad de Administración y Finanzas'), ('juridico', 'Unidad de Apoyo Jurídico'), ('control_interno', 'Órgano Interno de Control'), ('transparencia', 'Unidad de Transparencia'), ('informatica', 'Unidad de Apoyo Técnico e Informático'), ('voluntariado', 'Dirección de Voluntariado y Vinculación Institucional con Sociedad Civil'), ('alimentarios', 'Dirección de Servicios Alimentarios y Desarrollo Comunitario'), ('orientacion_familiar', 'Dirección de Orientación Familiar y Asistencia Social'), ('rehabilitacion', 'Dirección de Rehabilitación e Inclusión'), ('centros_asistenciales', 'Dirección de Centros Asistenciales'), ('proteccion_nna', 'Secretaria Ejecutiva del Sistema Estatal de Protección de los Derechos de Niñas, Niños y Adolescentes'), ('procuraduria_familia', 'Procuraduría Estatal de Protección de la Familia y de los Derechos de las Niñas, Niños y Adolescentes')], default='coordinacion_general', max_length=50, null=True),
        ),
    ]
